@echo off
echo Resetting Next.js project...

echo Removing .next directory...
rd /s /q .next

echo Removing node_modules\.cache...
rd /s /q node_modules\.cache

echo Installing dependencies...
call npm install

echo Starting development server...
call npm run dev
